project_bounds:
  latlon:
    - - -113.22853088
      - 41.78974484
    - - -113.22853088
      - 40.61186741
    - - -111.89918518
      - 40.61186741
    - - -111.89918518
      - 41.78974484
    - - -113.22853088
      - 41.78974484
  crs:
    "epsg:4326"
landsat:
  crs: "epsg:32612"
  # FYI: See https://github.com/yannforget/landsatxplore/tree/master for dataset IDs
  dataset: "landsat_ot_c2_l1" # Landsat 8 & 9 Collection 2 Level 1 & 2
  summary_file: "03_raw_data/Landsat/lansat_summary_2024-01-28.csv"
  bands:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B9
    - B10
    - B11
water_level:
  crs: "epsg:3857"
  shapefile: "03_raw_data/Utah_Great_Salt_Lake_Water_Level_2016/GSLWaterLevel2016.shp"
annotate_start_date: "2016-09-01"
annotate_end_date: "2016-11-30"
train:
  summary_file: "04_processed_data/landsat_train.csv"
test:
  summary_file: "04_processed_data/landsat_test.csv"
